
###FRONT
### pagina index
GET http://localhost:3000/

### pagina de reportes
GET http://localhost:3000/reportes

### pagina recepciones
GET http://localhost:3000/recepciones

## API
### recuperar informacion de los clientes
GET http://localhost:3000/api/clients

### recuperar informacion de un cliente
GET http://localhost:3000/api/clients/4

### recuperar informacion de varios clientes
GET http://localhost:3000/api/clients?ids=1,2,3,4

### recuperar informacion de los reportes
GET http://localhost:3000/api/devices

### recuperar informacion de los recepciones
GET http://localhost:3000/api/receptions

### recuperar informacion de varias recepciones
GET http://localhost:3000/api/receptions?ids=5,2,7,1

### recuperar informacion de los pagos
GET http://localhost:3000/api/payments