## API
### recuperar informacion de los clientes
GET http://localhost:3000/api/clients

### recuperar informacion de un cliente
GET http://localhost:3000/api/clients/180

### recuperar informacion de varios clientes
GET http://localhost:3000/api/clients?ids=150,4,151,200

### enviando informacion para agregar un client
POST http://localhost:3000/api/clients
Content-Type: application/json

{
    "name": "carlos",
    "phone": "12314513"
}

### enviando informacion para actualizar o agregar un client
PUT http://localhost:3000/api/clients/180
Content-Type: application/json

{
    "name": "jiren",
    "phone": "rentado",
    "apodo":"mariano el marciano"
    
}

### enviando informacion para actualizar parte de un client
PATCH http://localhost:3000/api/clients/180
Content-Type: application/json

{
    "name":"123"
}

### eliminar informacion de un cliente
DELETE http://localhost:3000/api/clients/180