## API
### recuperar informacion de los pagos
GET http://localhost:3000/api/payments

### recuperar informacion de varios pagos
GET http://localhost:3000/api/payments?method=BINANCE

### enviando informacion para agregar un pago
POST http://localhost:3000/api/payments
Content-Type: application/json,
access: asdpfijaogifj243i5j3245908230j2poifj08u243jskdjfwjj3ij2pkmfsdf

{
    "method": "callapa",
    "reference": "23424",
    "amoutBolivar": 324234,
    "amoutDolar": 23424,
    "saintInvoice": 123132,
    "receptionId": 1
}

### enviando informacion para actualizar o agregar un pago
PUT http://localhost:3000/api/payments/1
Content-Type: application/json

{
    "method": "pago mobil123",
    "reference": 3123444,
    "amoutBolivar": 13.21,
    "amoutDolar": 25.8,
    "saintInvoice": 1245213,
    "receptionId": 1
}

### enviando informacion para actualizar parte de un pago
PATCH http://localhost:3000/api/payments/3
Content-Type: application/json

{
    "receptionId": 1
}

### eliminar informacion de un pago
DELETE http://localhost:3000/api/payments/20